export enum TitleKeywords {
  salad = 'salad',
  soup = 'soup',
  burger = 'burger',
  stir_fry = 'stir-fry',
  curry = 'curry',
  tacos = 'tacos',
  noodles = 'noodles',
  pasta = 'pasta',
  risotto = 'risotto',
  pizza = 'pizza',
  steak = 'steak',
  pie = 'pie',
  bruschetta = 'bruschetta',
  quesadillas = 'quesadillas',
  stew = 'stew',
  wraps = 'wraps',
  gratin = 'gratin',
  halloumi = 'halloumi',
  rice_bowl = 'rice_bowl',
}
